name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/assessment:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/assessment:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker stop assessment || true
            docker rm assessment || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/assessment:latest
            docker run -d --name assessment \
              -p 8000:8000 \
              -e PORT=${{ secrets.PORT }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e JWT_ACCESS_TOKEN=${{ secrets.JWT_ACCESS_TOKEN }} \
              -e JWT_ACCESS_EXPIRE=${{ secrets.JWT_ACCESS_EXPIRE }} \
              -e JWT_REFRESH_TOKEN=${{ secrets.JWT_REFRESH_TOKEN }} \
              -e JWT_REFRESH_EXPIRE=${{ secrets.JWT_REFRESH_EXPIRE }} \
              -e EMAIL_HOST=${{ secrets.EMAIL_HOST }} \
              -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
              -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/assessment:latest
